name: deepberlin
channels:
  - defaults
dependencies:
  - ca-certificates=2019.5.15
  - certifi=2019.6.16
  - dask-core=2.1.0
  - dbus=1.13.6
  - decorator
  - defusedxml
  - expat
  - ffmpeg=4.0
  - fontconfig=2.13.0
  - hdf5=1.10.2
  - imageio=2.5.0
  - ipykernel=5.1.1
  - ipython=7.6.1
  - jupyter_client=5.3.1
  - jupyter_core=4.5.0
  - keras=2.2.4
  - matplotlib=3.1.0
  - nbconvert=5.5.0
  - nbformat=4.4.0
  - networkx=2.3
  - notebook=6.0.0
  - numpy=1.16.4
  - opencv=3.4.2
  - pandas=0.24.2
  - python=3.7.3
  - scikit-image=0.15.0
  - scikit-learn=0.21.2
  - scipy=1.3.0
  - seaborn=0.9.0
  - tensorflow
  - tqdm=4.32.1
  - pip
  - pip:
    - click==7.0
    - coverage==4.5.3
    - flake8==3.7.8
    - imagesize==1.1.0
    - pathlib2==2.3.4
    - requests==2.22.0
    - urllib3==1.24.3

